name: CODESTYLE

on:
  push:

jobs:
  lint:
    name: Run codestyle check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Python 3.6 ğŸ
        uses: actions/setup-python@v3
        with:
          python-version: 3.6.7

      - name: Install Dependencies ğŸ“¥
        run: pip install -r requirements.txt

      - name: Run Codestyle âœ”ï¸
        run: flake8 --max-line-length=160 --exclude venv,assets . && black --line-length=160 --check --exclude='/venv/|/assets/' .