name: CODESTYLE

on:
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
      - 'sources/translation.json'
      - 'locales/**'

jobs:
  lint:
    name: Run codestyle check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v6

      - name: Setup Python 3.13 ğŸ
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install Dependencies ğŸ“¥
        run: pip install -r requirements.txt

      - name: Run Codestyle âœ”ï¸
        run: flake8 --max-line-length=160 --exclude venv,assets . && black --line-length=160 --check --exclude='/venv/|/assets/' .
